#name: hello_cd

on: workflow_dispatch 

jobs:
#  cd:
#    uses: thethrowdown/new_change_test2/.github/workflows/managed-cd.yaml@main
#   secrets: inherit
 
 deploy:
    name: Deploy
    continue-on-error: true
    runs-on: ubuntu-latest
    #environment: prod             #Optional - tells github which environment this job runs on. 
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v1.34.2
        with:
          uses: thethrowdown/new_change_test2/.github/workflows/managed-cd.yaml@main
          secrets: inherit
          job-name: 'Deploy'
          
