#name: hello_cd

on: workflow_dispatch 

jobs:
 cd:
   uses: thethrowdown/new_change_test2/.github/workflows/managed-cd.yaml@main
   secrets: inherit
  
 my-job2:                         #Required - Defines a job named my-job. The child keys will define properties of the job.
    runs-on: ubuntu-latest        #Required - Configures the job to run on the latest version of an Ubuntu Linux runner. 
    #environment: prod             #Optional - tells github which environment this job runs on. 
    steps:                        #Required - Groups together all the steps that run in the my-job job defined above. 
      - name: my-step-2 
        run: echo "Hello World!"    #Optional - The run keyword tells the job to execute a command on the runner.
        job-name: 'Deploy'
