#name: hello_cd

on: workflow_dispatch 

jobs:

 deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow Change
        uses: thethrowdown/new_change_test2/.github/workflows/managed-cd.yaml@main
        secrets: inherit
        with:
          job-name: 'Deploy'
